FROM python:3.7-slim

RUN mkdir -p /app/.config \
    && chown -R 1001:1001 /app/.config \
    && chmod -R 755 /app/.config

RUN mkdir -p .rasa \
    && chown -R 1001:1001 .rasa \
    && chmod -R 755 .rasa

RUN python -m pip install --upgrade pip \
    && python -m pip install rasa

WORKDIR /app
ENV HOME=/app
COPY . .

USER 1001

RUN rasa train

ENTRYPOINT ["rasa"]
CMD ["run", "--enable-api", "--port", "8080"]